#Slack integration
notifications:
  slack: fiuba-studygroup:JCoNT2yk90mmc154Rh4nZgml

language: c++

sudo: required

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gcc
- sudo apt-get install -y libgflags-dev
- sudo apt-get install -y libsnappy-dev
- sudo apt-get install -y libbz2-dev

script:
- cd AppServer/build
- cmake ../src
- make
- cd ../..
- gcov AppServer/src/main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
