#Slack integration
notifications:
  slack: fiuba-studygroup:JCoNT2yk90mmc154Rh4nZgml

sudo: required

language: cpp

before_install:
- sudo sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list
- sudo sed -i 's/^#\s*\(deb.*multiverse\)$/\1/g' /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get -y install gcc-4.7 libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev

script:
- cd AppServer/build
- cmake ../src
- make
- cd ../..
- gcov AppServer/src/main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
