#Slack integration
notifications:
  slack: 7552-tallerii-2016-1c:89hUK2dxHbxNfpi9gPglcba8

sudo: required
dist: trusty

language: cpp

before_install:
- sudo sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list
- sudo sed -i 's/^#\s*\(deb.*multiverse\)$/\1/g' /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get -y install gcc g++ docker.io libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev
- sudo ./build-docker.sh

script:
- gcov AppServer/src/main.cpp
#- sudo ./run-server-docker.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
