#Slack integration
notifications:
  slack: fiuba-studygroup:JCoNT2yk90mmc154Rh4nZgml

language: c++

script:
- cd AppServer/build
- cmake ../src
- make
- cd ../..
- gcov AppServer/src/main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)