#Slack integration
notifications:
  slack: fiuba-studygroup:JCoNT2yk90mmc154Rh4nZgml

sudo: required

language: cpp

matrix:
  include:
    - os: linux
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'tuleu/precise-backports']
            packages: ['libbz2-dev', 'libsnappy-dev', 'libgflags-dev']

before_install:
- sudo apt-get install -y g++-4.8
- sudo apt-get install -y libgflags-dev
- sudo apt-get install -y libsnappy-dev
- sudo apt-get install -y libbz2-dev

script:
- cd AppServer/build
- cmake ../src
- make
- cd ../..
- gcov AppServer/src/main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
