#Slack integration
notifications:
  slack: fiuba-studygroup:JCoNT2yk90mmc154Rh4nZgml
    email: false
##############################

- Appserver/build/cmake
- Appserver/build/make
- Appserver/build/AppServer
- gcov Appserver/src/main.cpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash execute.sh